# TODO: Set force_ssl
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=800"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-From = "Netlify"

[[redirects]]
  from = "http://netlifyredirect1.allizom.org"
  to = "https://netlifyredirect1.allizom.org"

[[redirects]]
  from = "https://netlifyredirect1.allizom.org"
  to = "https://www.mozilla.org"

#[[redirects]]
#  from = "https://netlifyredirect2.allizom.org"
#  to = "https://www.mozilla.org"
#  [redirects.headers]
#    X-From = "Netlify"
#  # Always redirect even if it matches a local file
#  force = true
